apiVersion: v1
kind: ConfigMap
metadata:
  name: bugdrill-api-config
  namespace: bugdrill
data:
  DB_HOST: "bugdrill-postgres-postgresql"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "bugdrill"
  REDIS_HOST: "bugdrill-redis-master"
  REDIS_PORT: "6379"
  JWT_SECRET: "local-dev-secret-key-change-in-production"
  EXECUTOR_URL: "http://bugdrill-executor:8081"
---
apiVersion: v1
kind: Secret
metadata:
  name: bugdrill-api-secret
  namespace: bugdrill
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugdrill-api
  namespace: bugdrill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugdrill-api
  template:
    metadata:
      labels:
        app: bugdrill-api
    spec:
      containers:
      - name: bugdrill-api
        image: smithaavinash/bugdrill-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: bugdrill-api-config
        - secretRef:
            name: bugdrill-api-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bugdrill-api
  namespace: bugdrill
spec:
  selector:
    app: bugdrill-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
